// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: saZG5UFzSFK9GHv1WC5GrQ
// Component: 5tZJBPBuhZhT

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TestComponent from "../../TestComponent"; // plasmic-import: gR2GHBg2tIV4/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: saZG5UFzSFK9GHv1WC5GrQ/projectcss
import sty from "./PlasmicTestArenaComponent.module.css"; // plasmic-import: 5tZJBPBuhZhT/css

createPlasmicElementProxy;

export type PlasmicTestArenaComponent__VariantMembers = {};
export type PlasmicTestArenaComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestArenaComponent__VariantsArgs;
export const PlasmicTestArenaComponent__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTestArenaComponent__ArgsType = {};
type ArgPropType = keyof PlasmicTestArenaComponent__ArgsType;
export const PlasmicTestArenaComponent__ArgProps = new Array<ArgPropType>();

export type PlasmicTestArenaComponent__OverridesType = {
  root?: Flex__<"div">;
  testcompinst1?: Flex__<typeof TestComponent>;
};

export interface DefaultTestArenaComponentProps {
  className?: string;
}

const $$ = {};

function PlasmicTestArenaComponent__RenderFunc(props: {
  variants: PlasmicTestArenaComponent__VariantsArgs;
  args: PlasmicTestArenaComponent__ArgsType;
  overrides: PlasmicTestArenaComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <TestComponent
        data-plasmic-name={"testcompinst1"}
        data-plasmic-override={overrides.testcompinst1}
        className={classNames("__wab_instance", sty.testcompinst1)}
        testDateRangeProp={[
          "2024-08-14T22:50:14.157Z",
          "2024-08-15T04:04:00.943Z"
        ]}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "testcompinst1"],
  testcompinst1: ["testcompinst1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  testcompinst1: typeof TestComponent;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestArenaComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestArenaComponent__VariantsArgs;
    args?: PlasmicTestArenaComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestArenaComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTestArenaComponent__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestArenaComponent__ArgProps,
          internalVariantPropNames: PlasmicTestArenaComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestArenaComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestArenaComponent";
  } else {
    func.displayName = `PlasmicTestArenaComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicTestArenaComponent = Object.assign(
  // Top-level PlasmicTestArenaComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    testcompinst1: makeNodeComponent("testcompinst1"),

    // Metadata about props expected for PlasmicTestArenaComponent
    internalVariantProps: PlasmicTestArenaComponent__VariantProps,
    internalArgProps: PlasmicTestArenaComponent__ArgProps
  }
);

export default PlasmicTestArenaComponent;
/* prettier-ignore-end */
