// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: saZG5UFzSFK9GHv1WC5GrQ
// Component: FgdJQ-O33OIy

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TestComponent from "../../TestComponent"; // plasmic-import: gR2GHBg2tIV4/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: saZG5UFzSFK9GHv1WC5GrQ/projectcss
import sty from "./PlasmicTestPage.module.css"; // plasmic-import: FgdJQ-O33OIy/css

createPlasmicElementProxy;

export type PlasmicTestPage__VariantMembers = {};
export type PlasmicTestPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestPage__VariantsArgs;
export const PlasmicTestPage__VariantProps = new Array<VariantPropType>();

export type PlasmicTestPage__ArgsType = {};
type ArgPropType = keyof PlasmicTestPage__ArgsType;
export const PlasmicTestPage__ArgProps = new Array<ArgPropType>();

export type PlasmicTestPage__OverridesType = {
  root?: Flex__<"div">;
  testComponent?: Flex__<typeof TestComponent>;
};

export interface DefaultTestPageProps {
  className?: string;
}

const $$ = {};

function PlasmicTestPage__RenderFunc(props: {
  variants: PlasmicTestPage__VariantsArgs;
  args: PlasmicTestPage__ArgsType;
  overrides: PlasmicTestPage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <TestComponent
            data-plasmic-name={"testComponent"}
            data-plasmic-override={overrides.testComponent}
            className={classNames("__wab_instance", sty.testComponent)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "testComponent"],
  testComponent: ["testComponent"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  testComponent: typeof TestComponent;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestPage__VariantsArgs;
    args?: PlasmicTestPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTestPage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestPage__ArgProps,
          internalVariantPropNames: PlasmicTestPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestPage";
  } else {
    func.displayName = `PlasmicTestPage.${nodeName}`;
  }
  return func;
}

export const PlasmicTestPage = Object.assign(
  // Top-level PlasmicTestPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    testComponent: makeNodeComponent("testComponent"),

    // Metadata about props expected for PlasmicTestPage
    internalVariantProps: PlasmicTestPage__VariantProps,
    internalArgProps: PlasmicTestPage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTestPage;
/* prettier-ignore-end */
